language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y maven2
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql travis_ci_test -U postgres < ./dspace/etc/postgres/database_create_doi_table.sql
  - export M2_HOME=/usr/share/maven2
  - export M2=/usr/share/maven2
install: true
script: "/usr/bin/mvn package -P postgres -Dmaven.test.skip=false -Ddefault.dspace.dir=../../../../test"
