language: java
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres'
  - psql travis_ci_test -U postgres < ./dspace/etc/postgres/database_create_doi_table.sql
script: "mvn package -P postgres -Dmaven.test.skip=false -Ddefault.dspace.dir=./test"