language: java
before_install:
  - ./install-maven.sh
  - psql -U postgres -c 'create database travis_ci_test;'
  - psql travis_ci_test -U postgres < ./dspace/etc/postgres/database_create_doi_table.sql
  - export M2="$TRAVIS_BUILD_DIR/apache-maven-2.2.1"
  - export M2_HOME="$TRAVIS_BUILD_DIR/apache-maven-2.2.1"
install: true
script: "$TRAVIS_BUILD_DIR/apache-maven-2.2.1/bin/mvn package -P postgres -Dmaven.test.skip=false -Ddefault.dspace.dir=$TRAVIS_BUILD_DIR/test"
