language: java
jdk: openjdk6
before_install:
  - ./test/bin/travis-install-maven.sh
  - psql -U postgres -c "create user dryad_test_user with createdb;"
  - createdb -U dryad_test_user travis_ci_test
  - psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_schema.sql
  - psql dryad_test -U dryad_test_user < ./dspace/etc/postgres/database_create_doi_table.sql
  - export PATH="$TRAVIS_BUILD_DIR/apache-maven-2.2.1/bin:$PATH"
install:
  - ./test/bin/travis-install-missing-poms.sh
  - ./test/bin/travis-install-dryad-dir.sh
script: mvn package -Dmaven.test.skip=false -Ddefault.dspace.dir=/opt/dryad-test

